name = "Expedition Pack"
author = "Sorrento110"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0cbd3a6281213f3c2bafadf862a3bd0bc32129ac3724c3d39205045cb52a111"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
