name = "Expedition Pack"
author = "Sorrento110"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0b97d804f49d20181817f613b5967cd93bfaf02811e3617f34024528fe776a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
