name = "Expedition Pack"
author = "Sorrento110"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "811d18cf2e97181a5a4b940213b4a3874ff8179afa712f328489336c629c68bc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
