name = "Expedition Pack"
author = "Sorrento110"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f577d317363eee818c534af2b249913085313bb54ab0d5b76119aaf1ba93d41"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
