name = "Expedition Pack"
author = "Sorrento110"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fa5552aa7dbbf8acc3712bbb3f777ae1261202b5c3b68abcea37ae42a2c64b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
